# This file has been autogenerated by the pywayland scanner

# Copyright © 2008-2011 Kristian Høgsberg
# Copyright © 2010-2011 Intel Corporation
# Copyright © 2012-2013 Collabora, Ltd.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice (including the
# next paragraph) shall be included in all copies or substantial
# portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import (
    Argument,
    ArgumentType,
    Global,
    Interface,
    Proxy,
    Resource,
)

from .wl_registry import WlRegistry


class WlFixes(Interface):
    """Wayland protocol fixes

    This global fixes problems with other core-protocol interfaces that cannot
    be fixed in these interfaces themselves.
    """

    name = "wl_fixes"
    version = 2

    class error(enum.IntEnum):
        invalid_ack_remove = 0


class WlFixesProxy(Proxy[WlFixes]):
    interface = WlFixes

    @WlFixes.request()
    def destroy(self) -> None:
        """Destroys this object
        """
        self._marshal(0)
        self._destroy()

    @WlFixes.request(
        Argument(ArgumentType.Object, interface=WlRegistry),
    )
    def destroy_registry(self, registry: WlRegistry) -> None:
        """Destroy a :class:`~pywayland.protocol.wayland.WlRegistry`

        This request destroys a :class:`~pywayland.protocol.wayland.WlRegistry`
        object.

        The client should no longer use the
        :class:`~pywayland.protocol.wayland.WlRegistry` after making this
        request.

        The compositor will emit a :func:`WlDisplay.delete_id()
        <pywayland.protocol.wayland.WlDisplay.delete_id>` event with the object
        ID of the registry and will no longer emit any events on the registry.
        The client should re-use the object ID once it receives the
        :func:`WlDisplay.delete_id()
        <pywayland.protocol.wayland.WlDisplay.delete_id>` event.

        :param registry:
            the registry to destroy
        :type registry:
            :class:`~pywayland.protocol.wayland.WlRegistry`
        """
        self._marshal(1, registry)

    @WlFixes.request(
        Argument(ArgumentType.Object, interface=WlRegistry),
        Argument(ArgumentType.Uint),
        version=2,
    )
    def ack_global_remove(self, registry: WlRegistry, name: int) -> None:
        """Acknowledge global removal

        Acknowledge the removal of the specified global.

        If no global with the specified name exists or the global is not
        removed, the :func:`WlFixes.invalid_ack_remove()` protocol error will
        be posted.

        Due to the Wayland protocol being asynchronous, the wl_global objects
        cannot be destroyed immediately. For example, if a wl_global is removed
        and a client attempts to bind that global around same time, it can
        result in a protocol error due to an unknown global name in the bind
        request.

        In order to avoid crashing clients, the compositor should remove the
        wl_global once it is guaranteed that no more bind requests will come.

        The :func:`WlFixes.ack_global_remove()()` request is used to signal to
        the compositor that the client will not bind the given global anymore.
        After all clients acknowledge the removal of the global, the compositor
        can safely destroy it.

        The client must call the :func:`WlFixes.ack_global_remove()()` request
        in response to a :func:`WlRegistry.global_remove()()
        <pywayland.protocol.wayland.WlRegistry.global_remove()>` event even if
        it did not bind the corresponding global.

        :param registry:
            the registry object
        :type registry:
            :class:`~pywayland.protocol.wayland.WlRegistry`
        :param name:
            unique name of the global
        :type name:
            `ArgumentType.Uint`
        """
        self._marshal(2, registry, name)


class WlFixesResource(Resource):
    interface = WlFixes


class WlFixesGlobal(Global):
    interface = WlFixes


WlFixes._gen_c()
WlFixes.proxy_class = WlFixesProxy
WlFixes.resource_class = WlFixesResource
WlFixes.global_class = WlFixesGlobal
