

ADB_KEY_MAP = {
    'esc': 'KEYCODE_ESCAPE',
    'enter': 'KEYCODE_ENTER',
    'return': 'KEYCODE_ENTER',
    'space': 'KEYCODE_SPACE',
    'backspace': 'KEYCODE_DEL',
    'delete': 'KEYCODE_FORWARD_DEL',
    'tab': 'KEYCODE_TAB',
    'home': 'KEYCODE_HOME',
    'pageup': 'KEYCODE_PAGE_UP',
    'page_up': 'KEYCODE_PAGE_UP',
    'pagedown': 'KEYCODE_PAGE_DOWN',
    'page_down': 'KEYCODE_PAGE_DOWN',
    'up': 'KEYCODE_DPAD_UP',
    'down': 'KEYCODE_DPAD_DOWN',
    'left': 'KEYCODE_DPAD_LEFT',
    'right': 'KEYCODE_DPAD_RIGHT',
    'alt': 'KEYCODE_ALT_LEFT',
    'lalt': 'KEYCODE_ALT_LEFT',
    'alt_l': 'KEYCODE_ALT_LEFT',
    'ralt': 'KEYCODE_ALT_RIGHT',
    'alt_r': 'KEYCODE_ALT_RIGHT',
    'alt_gr': 'KEYCODE_ALT_RIGHT',
    'ctrl': 'KEYCODE_CTRL_LEFT',
    'control': 'KEYCODE_CTRL_LEFT',
    'lctrl': 'KEYCODE_CTRL_LEFT',
    'lcontrol': 'KEYCODE_CTRL_LEFT',
    'ctrl_l': 'KEYCODE_CTRL_LEFT',
    'rctrl': 'KEYCODE_CTRL_RIGHT',
    'rcontrol': 'KEYCODE_CTRL_RIGHT',
    'ctrl_r': 'KEYCODE_CTRL_RIGHT',
    'shift': 'KEYCODE_SHIFT_LEFT',
    'lshift': 'KEYCODE_SHIFT_LEFT',
    'shift_l': 'KEYCODE_SHIFT_LEFT',
    'rshift': 'KEYCODE_SHIFT_RIGHT',
    'shift_r': 'KEYCODE_SHIFT_RIGHT',
    'capslock': 'KEYCODE_CAPS_LOCK',
    'caps_lock': 'KEYCODE_CAPS_LOCK',
    'numlock': 'KEYCODE_NUM_LOCK',
    'num_lock': 'KEYCODE_NUM_LOCK',
    'scrolllock': 'KEYCODE_SCROLL_LOCK',
    'scroll_lock': 'KEYCODE_SCROLL_LOCK',
    'printscreen': 'KEYCODE_SYSRQ',
    'print_screen': 'KEYCODE_SYSRQ',
}
