import sys

if sys.platform != "win32":
    raise ImportError(f"{__file__} is Windows-only")

import win32con

PYDIRECT_KEY_MAP = {
    'alt_l': 'altleft',
    'alt_r': 'altright',
    'lalt': 'altleft',
    'ralt': 'altright',
    'ctrl_l': 'ctrlleft',
    'ctrl_r': 'ctrlright',
    'lctrl': 'ctrlleft',
    'rctrl': 'ctrlright',
    'lcontrol': 'ctrlleft',
    'rcontrol': 'ctrlright',
    'shift_l': 'shiftleft',
    'shift_r': 'shiftright',
    'lshift': 'shiftleft',
    'rshift': 'shiftright',
    'page_up': 'pageup',
    'page_down': 'pagedown',
    'caps_lock': 'capslock',
    'num_lock': 'numlock',
    'scroll_lock': 'scrolllock',
    'print_screen': 'printscreen',
    'cmd': 'win',
    'cmd_l': 'win',
    'cmd_r': 'win',
    'command': 'win',
    'meta': 'win',
    'windows': 'win',
}


def normalize_pydirect_key(key):
    key = str(key)
    return PYDIRECT_KEY_MAP.get(key.lower(), key)


vk_key_dict = {
    'F1': win32con.VK_F1,
    'F2': win32con.VK_F2,
    'F3': win32con.VK_F3,
    'F4': win32con.VK_F4,
    'F5': win32con.VK_F5,
    'F6': win32con.VK_F6,
    'F7': win32con.VK_F7,
    'F8': win32con.VK_F8,
    'F9': win32con.VK_F9,
    'F10': win32con.VK_F10,
    'F11': win32con.VK_F11,
    'F12': win32con.VK_F12,
    'ESC': win32con.VK_ESCAPE,
    'CTRL': win32con.VK_CONTROL,
    'CONTROL': win32con.VK_CONTROL,
    'LCTRL': win32con.VK_LCONTROL,
    'RCTRL': win32con.VK_RCONTROL,
    'CTRL_L': win32con.VK_LCONTROL,
    'CTRL_R': win32con.VK_RCONTROL,
    'LCONTROL': win32con.VK_LCONTROL,
    'RCONTROL': win32con.VK_RCONTROL,
    'ALT': win32con.VK_MENU,
    'LALT': win32con.VK_LMENU,
    'RALT': win32con.VK_RMENU,
    'ALT_L': win32con.VK_LMENU,
    'ALT_R': win32con.VK_RMENU,
    'SHIFT': win32con.VK_SHIFT,
    'LSHIFT': win32con.VK_LSHIFT,
    'RSHIFT': win32con.VK_RSHIFT,
    'SHIFT_L': win32con.VK_LSHIFT,
    'SHIFT_R': win32con.VK_RSHIFT,
    'TAB': win32con.VK_TAB,
    'ENTER': win32con.VK_RETURN,
    'RETURN': win32con.VK_RETURN,
    'SPACE': win32con.VK_SPACE,
    'LEFT': win32con.VK_LEFT,
    'UP': win32con.VK_UP,
    'RIGHT': win32con.VK_RIGHT,
    'DOWN': win32con.VK_DOWN,
    'BACKSPACE': win32con.VK_BACK,
    'PAGEUP': win32con.VK_PRIOR,
    'PAGE_UP': win32con.VK_PRIOR,
    'PAGEDOWN': win32con.VK_NEXT,
    'PAGE_DOWN': win32con.VK_NEXT,
    'HOME': win32con.VK_HOME,
    'END': win32con.VK_END,
    'INSERT': win32con.VK_INSERT,
    'DELETE': win32con.VK_DELETE,
    'CAPSLOCK': win32con.VK_CAPITAL,
    'CAPS_LOCK': win32con.VK_CAPITAL,
    'NUMLOCK': win32con.VK_NUMLOCK,
    'NUM_LOCK': win32con.VK_NUMLOCK,
    'SCROLLLOCK': win32con.VK_SCROLL,
    'SCROLL_LOCK': win32con.VK_SCROLL,
    'PRINTSCREEN': win32con.VK_SNAPSHOT,
    'PRINT_SCREEN': win32con.VK_SNAPSHOT,
    'WIN': win32con.VK_LWIN,
    'WINDOWS': win32con.VK_LWIN,
    'COMMAND': win32con.VK_LWIN,
    'CMD': win32con.VK_LWIN,
    'CMD_L': win32con.VK_LWIN,
    'CMD_R': win32con.VK_RWIN,
    'META': win32con.VK_LWIN,
}
